name: Update Data

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    
    - name: Ensure directories exist
      run: |
        mkdir -p data
        mkdir -p data/images
    
    - name: Run crawler script
      run: python -m scripts
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add data/index*.json data/images/ index.html
        git commit -m "Update catalogs, index.html and images" || exit 0
        git push

permissions:
  contents: write 